### ISSUE TITLE
.dylib module for MacOSX

### ISSUE THREAD

**Issue by zeronone** [dzop/emacs-zmq#19]
I am using emacs 28, currently its `module-file-suffix` is configured as `.dylib`, however `emacs-zmq` release assets only contains `.so` module file. Is it possible to include a `.dylib` module too (or are there any build instructions?). 

From emacs documentation:
```
 -- Variable: module-file-suffix
     This variable holds the system-dependent value of the file-name
     extension of the module files.  Its value is ‘.so’ on POSIX hosts,
     ‘.dylib’ on macOS, and ‘.dll’ on MS-Windows.

   On macOS, dynamic modules can also have the suffix ‘.so’ in addition
to ‘.dylib’.
```

Simply changing `module-file-suffix` to `.so` causes the following error on module load.
```
dyld: lazy symbol binding failed: Symbol not found: _zmq_ctx_new
  Referenced from: /Users/st21371/.emacs.d/.local/straight/build/zmq/emacs-zmq.so
  Expected in: flat namespace

dyld: Symbol not found: _zmq_ctx_new
  Referenced from: /Users/st21371/.emacs.d/.local/straight/build/zmq/emacs-zmq.so
  Expected in: flat namespace
```

**Comment by nnicandro** [comment]
You can build the module manually with

```bash
cd ~/path/to/emacs-zmq
rm emacs-zmq.so # remove the old module
make # build a new one
```

But I think .so and .dylb are treated the same by Emacs when actually loading the module, i.e. all they did was allow a module file name to have a .dylb extension, see https://github.com/emacs-mirror/emacs/commit/28268e47d844215b11f9a731d2bedb58bee0b343.

Do you get the error when using Emacs 27 or 26.3 on the same OS? Also what macOS version are you on? Catalina?

**Comment by matteha** [comment]
Getting the same error unfortunately, not sure how to fix this with Emacs 28. No errors on Emacs 26 / 27. I am on Catalina. Love the jupyter package!

**Comment by prasoon2211** [comment]
Hi, is there a solution to this yet? I tried building from source and I only get a `emacs-zmq.so` in output. Is there any way to build a `dylib` file?

**Comment by sprig** [comment]
Same issue on Emacs 28 on Catalina.
For me, a workaround that worked was to copy `emacs-zmq.so` to `emacs-zmq.dylib`, and then everything appears to load without issue.

**Comment by lccambiaghi** [comment]
@sprig you, kind anonymous of the internet, just made my day. Thank you

**Comment by memeplex** [comment]
Hi, I'm still seeing this in emacs built from the emacs-28 branch:

```
Downloading https://github.com/nnicandro/emacs-zmq/releases/download/v0.10.10/emacs-zmq-x86_64-apple-darwin17.4.0.tar.gz
Verifying sha256 signature of emacs-zmq-x86_64-apple-darwin17.4.0.tar.gz
Wrote /Users/carlos/.emacs.d/straight/build/zmq/emacs-zmq-x86_64-apple-darwin17.4.0.tar.gz
uncompressing emacs-zmq-x86_64-apple-darwin17.4.0.tar.gz...done
Parsing tar file...done
Extracting...done
zmq--download-module: Opening input file: No such file or directory, /Users/carlos/.emacs.d/straight/build/zmq/emacs-zmq-x86_64-apple-darwin17.4.0/emacs-zmq.dylib
```

```
❯ tar zxvf emacs-zmq-x86_64-apple-darwin17.4.0.tar.gz
x emacs-zmq-x86_64-apple-darwin17.4.0/
x emacs-zmq-x86_64-apple-darwin17.4.0/emacs-zmq.so
```

```
❯ ls /Users/carlos/.emacs.d/straight/build/zmq/emacs-zmq-x86_64-apple-darwin17.4.0/emacs-zmq.so
/Users/carlos/.emacs.d/straight/build/zmq/emacs-zmq-x86_64-apple-darwin17.4.0/emacs-zmq.so
```

**Comment by memeplex** [comment]
I believe the problem is with the downloaded version, if I instead:

```
Check for compatible module binary to download? (y or n) n
ZMQ module not found. Build it? (y or n) y
```

Then the version built from sources works just fine.

BTW, if I had installed libzmq from brew would it just work without requiring any download or extra build?

**Comment by NightMachinery** [comment]
I get
```
Error in private config: config.el, (args-out-of-range  *tar-data emacs-zmq-x86_64-apple-darwin17.4.0.tar.gz* #<marker at 513 in  *tar-data emacs-zmq-x86_64-apple-darwin17.4.0.tar.gz*> 106255965280)
```

Even though I have copied the `.so` file to a `.dylib` file, too:
```
~/.emacs.d/.local/straight/build-28.1/zmq/emacs-zmq-x86_64-apple-darwin17.4.0 master
 ❯ ls
.  ..  emacs-zmq.dylib  emacs-zmq.so
```

Might be the  same bug as https://github.com/nnicandro/emacs-zmq/issues/20 .

Update: After manually running `make` in `~/.emacs.d/.local/straight/build-28.1/zmq`, the problem was resolved. I think the problem was that `emacs-zmq.dylib` should have been in `./`, not `./emacs-zmq-x86_64-apple-darwin17.4.0`.
