### ISSUE TITLE
Unable to download module binary or compile the module.

### ISSUE THREAD

**Issue by aNaravi** [dzop/emacs-zmq#25]
I'm trying to set up emacs-jupyter with use-package. When emacs-zmq is automatically downloaded, it throws up this message:

![zmq](https://user-images.githubusercontent.com/5837517/100535645-ca675f00-3240-11eb-9de6-67088989c947.png)

However, either the module binary doesn't download or it isn't loaded properly because the message keeps popping up repeatedly until I click 'no'.
_Note: I tried doing this within a docker container and it did download the module binary successfully._

Next, when the module binary wasn't downloaded, it asked me to compile the module directly but I got this compilation error:

```
-*- mode: compilation; default-directory: "~/.emacs.d/elpa/zmq-0.10.10/" -*-
Compilation started at Sun Nov 29 10:12:36

make EMACS=/usr/local/lib/emacs/26.3/bin/emacs-26.3
cd src && autoreconf -i
aclocal: warning: couldn't open directory 'm4': No such file or directory
configure.ac:8: installing './ar-lib'
configure.ac:7: installing './compile'
configure.ac:9: installing './config.guess'
configure.ac:9: installing './config.sub'
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
Makefile.am:4: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:4:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:4:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:4:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:4:   its definition is in aclocal's search path.
Makefile.am: installing './depcomp'
autoreconf: automake failed with exit status: 1
make: *** [Makefile:63: src/configure] Error 1

Compilation exited abnormally with code 2 at Sun Nov 29 10:12:39
```

Why does this emacs package install successfully in a docker container while failing to install normally? Do I need root access?

**Comment by arvids** [comment]
Did you find a solution to this?

**Comment by dalanicolai** [comment]
It requires `libtool` to be installed, however after installing libtool the build still fails (for me on Fedora 35).

But as mentioned in the [installation instructions](https://github.com/nnicandro/emacs-zmq#installation), you can also simply download the `.dll/.so` file from [here](https://github.com/nnicandro/emacs-zmq/releases) and place it in the directory containing the `zmq.el` file.

It is worth it because, if used for emacs-jupyter, that package works great! (Thanks for these packages!)

**Comment by nakkaya** [comment]
@aNaravi @arvids  Had the same problem on Ubuntu `arm64`.  Navigating into package directory under `~/.emacs.d/` and running the following under `src` folder fixed the issue,

    libtoolize \
    && aclocal \
    && automake --add-missing \
    && autoconf

**Comment by aNaravi** [comment]
Sorry for the late response.
I had switched to a new package manager, [straight.el](https://github.com/raxod502/straight.el), shortly after I had posted this issue and it had gone away.

@nakkaya thanks for the solution.
