### ISSUE TITLE
Building emacs-zmq module binaries for Windows platforms

### ISSUE THREAD

**Issue by nnicandro** [dzop/emacs-zmq#3]
Travis has the option of [uploading binaries to Github](https://docs.travis-ci.com/user/deployment/releases). This would enable supporting Windows platforms.

What we could do is install the `mingw-w64` cross compilers with the following in Travis

```yaml
addons:
  apt:
    packages:
      - mingw-w64
```

Then we would have to modify `src/configure.ac` to pass `LC_INIT([win32-dll])` instead of `LC_INIT([shared])` if cross compiling for Windows. Also we would have to make a modification to `src/Makefile.am`, see the note on `win32-dll` at https://www.gnu.org/software/libtool/manual/html_node/LT_005fINIT.html.

Then to do the cross compiling we would have to pass the `--host=i686-w64-mingw32` or `--host=x86_64-w64-mingw32` options to the `configure` scripts. Both for the `emacs-zmq` module and `libzmq`.

It would also make sense to link a static `libzmq` into `emacs-zmq` so that all that is required for users is to download a pre-compiled `emacs-zmq`.

EDIT: This actually looks like it is [not possible](https://github.com/zeromq/libzmq/blob/0761e6bb48e34c1499104eaf7f9daa0c6647977c/acinclude.m4#L5), so we would have to provide both a pre-compiled `libzmq` and `emacs-zmq`.

After doing all of the above, the built `emacs-zmq` module can be uploaded to Github.

**Comment by nnicandro** [comment]
Also see https://grokbase.com/t/zeromq/zeromq-dev/13a1mha9ft/czmq-windows-build for some info on including `libstdc++` and `libgcc` for `libzmq`.

**Comment by fleimgruber** [comment]
I would love to see this working on Windows. I was just experimenting with building binaries on MSYS2 using the MinGW64 toolchain. I made the changes you suggested on `LT_INIT([win32-dll disable-static])` and `-no-undefined`. Compilation works, but I get the following error when I `(use-package zmq)`:

```
Debugger entered--Lisp error: (void-variable MZ)
  eval-buffer(#<buffer  *load*-397321> nil "c:/Users/user/.spacemacs.d/layers/user/local/emacs-zmq/emacs-zmq.dll" nil t)  ; Reading at buffer position 4
  load-with-code-conversion("c:/Users/user/.spacemacs.d/layers/user/local/emacs-zmq/emacs-zmq.dll" "c:/Users/user/.spacemacs.d/layers/user/local/emacs-zmq/emacs-zmq.dll" nil nil)
  #<subr load>("c:/Users/user/.spacemacs.d/layers/user/local/emacs-zmq/emacs-zmq.dll" nil nil t nil)
  apply(#<subr load> ("c:/Users/user/.spacemacs.d/layers/user/local/emacs-zmq/emacs-zmq.dll" nil nil t))
  load("c:/Users/user/.spacemacs.d/layers/user/local/emacs-zmq/emacs-zmq.dll" nil nil t)
  load-file("c:/Users/user/.spacemacs.d/layers/user/local/emacs-zmq/emacs-zmq.dll")
  (progn (load-file zmq-module-file) (add-hook 'post-gc-hook (function zmq--cleanup-globrefs)))
  (if (file-exists-p zmq-module-file) (progn (load-file zmq-module-file) (add-hook 'post-gc-hook (function zmq--cleanup-globrefs))) (if (y-or-n-p "ZMQ module not found. Build it? ") (progn (let ((default-directory (file-name-directory (locate-library "zmq")))) (let (--cl-load-zmq--) (setq --cl-load-zmq-- (function (lambda (_buf status) (progn (if (string= status "finished\n") (zmq-load) (message "Something went wrong when compiling the ZMQ module!")) (remove-hook 'compilation-finish-functions --cl-load-zmq--) (exit-recursive-edit))))) (add-hook 'compilation-finish-functions --cl-load-zmq--) (compile "make") (recursive-edit))))))
  (if zmq-module-file (if (file-exists-p zmq-module-file) (progn (load-file zmq-module-file) (add-hook 'post-gc-hook (function zmq--cleanup-globrefs))) (if (y-or-n-p "ZMQ module not found. Build it? ") (progn (let ((default-directory (file-name-directory (locate-library "zmq")))) (let (--cl-load-zmq--) (setq --cl-load-zmq-- (function (lambda (_buf status) (progn (if (string= status "finished\n") (zmq-load) (message "Something went wrong when compiling the ZMQ module!")) (remove-hook 'compilation-finish-functions --cl-load-zmq--) (exit-recursive-edit))))) (add-hook 'compilation-finish-functions --cl-load-zmq--) (compile "make") (recursive-edit)))))) (user-error "Modules are not supported"))
  zmq-load()
  eval-buffer(#<buffer  *load*> nil "c:/Users/user/.spacemacs.d/layers/user/local/emacs-zmq/zmq.el" nil t)  ; Reading at buffer position 22006
  load-with-code-conversion("c:/Users/user/.spacemacs.d/layers/user/local/emacs-zmq/zmq.el" "c:/Users/user/.spacemacs.d/layers/user/local/emacs-zmq/zmq.el" t t)
  #<subr require>(zmq nil t)
  apply(#<subr require> (zmq nil t))
  require(zmq nil t)
  (not (require 'zmq nil t))
  (if (not (require 'zmq nil t)) (display-warning 'use-package (format "Cannot load %s" 'zmq) :error))
  (progn (condition-case err (if (run-hook-with-args-until-failure 'use-package--zmq--pre-init-hook) (progn (run-hooks 'use-package--zmq--post-init-hook))) ((debug error) (funcall use-package--warning324 :init err))) (if (not (require 'zmq nil t)) (display-warning 'use-package (format "Cannot load %s" 'zmq) :error)))
  (condition-case err (progn (condition-case err (if (run-hook-with-args-until-failure 'use-package--zmq--pre-init-hook) (progn (run-hooks 'use-package--zmq--post-init-hook))) ((debug error) (funcall use-package--warning324 :init err))) (if (not (require 'zmq nil t)) (display-warning 'use-package (format "Cannot load %s" 'zmq) :error))) ((debug error) (funcall use-package--warning324 :catch err)))
  (progn (defvar use-package--warning324 (function (lambda (keyword err) (let ((msg (format "%s/%s: %s" 'zmq keyword (error-message-string err)))) (display-warning 'use-package msg :error))))) (condition-case err (progn (condition-case err (if (run-hook-with-args-until-failure 'use-package--zmq--pre-init-hook) (progn (run-hooks 'use-package--zmq--post-init-hook))) ((debug error) (funcall use-package--warning324 :init err))) (if (not (require 'zmq nil t)) (display-warning 'use-package (format "Cannot load %s" 'zmq) :error))) ((debug error) (funcall use-package--warning324 :catch err))))
  eval((progn (defvar use-package--warning324 (function (lambda (keyword err) (let ((msg (format "%s/%s: %s" 'zmq keyword (error-message-string err)))) (display-warning 'use-package msg :error))))) (condition-case err (progn (condition-case err (if (run-hook-with-args-until-failure 'use-package--zmq--pre-init-hook) (progn (run-hooks 'use-package--zmq--post-init-hook))) ((debug error) (funcall use-package--warning324 :init err))) (if (not (require 'zmq nil t)) (display-warning 'use-package (format "Cannot load %s" 'zmq) :error))) ((debug error) (funcall use-package--warning324 :catch err)))) nil)
  elisp--eval-last-sexp(nil)
  #f(compiled-function (eval-last-sexp-arg-internal) "Evaluate sexp before point; print value in the echo area.\nInteractively, with a non `-' prefix argument, print output into\ncurrent buffer.\n\nNormally, this function truncates long output according to the\nvalue of the variables `eval-expression-print-length' and\n`eval-expression-print-level'.  With a prefix argument of zero,\nhowever, there is no such truncation.  Such a prefix argument\nalso causes integers to be printed in several additional formats\n(octal, hexadecimal, and character when the prefix argument is\n-1 or the integer is `eval-expression-print-maximum-character' or\nless).\n\nIf `eval-expression-debug-on-error' is non-nil, which is the default,\nthis command arranges for all errors to enter the debugger." (interactive "P") #<bytecode 0x1000d3153>)(nil)
  ad-Advice-eval-last-sexp(#f(compiled-function (eval-last-sexp-arg-internal) "Evaluate sexp before point; print value in the echo area.\nInteractively, with a non `-' prefix argument, print output into\ncurrent buffer.\n\nNormally, this function truncates long output according to the\nvalue of the variables `eval-expression-print-length' and\n`eval-expression-print-level'.  With a prefix argument of zero,\nhowever, there is no such truncation.  Such a prefix argument\nalso causes integers to be printed in several additional formats\n(octal, hexadecimal, and character when the prefix argument is\n-1 or the integer is `eval-expression-print-maximum-character' or\nless).\n\nIf `eval-expression-debug-on-error' is non-nil, which is the default,\nthis command arranges for all errors to enter the debugger." (interactive "P") #<bytecode 0x1000d3153>) nil)
  apply(ad-Advice-eval-last-sexp #f(compiled-function (eval-last-sexp-arg-internal) "Evaluate sexp before point; print value in the echo area.\nInteractively, with a non `-' prefix argument, print output into\ncurrent buffer.\n\nNormally, this function truncates long output according to the\nvalue of the variables `eval-expression-print-length' and\n`eval-expression-print-level'.  With a prefix argument of zero,\nhowever, there is no such truncation.  Such a prefix argument\nalso causes integers to be printed in several additional formats\n(octal, hexadecimal, and character when the prefix argument is\n-1 or the integer is `eval-expression-print-maximum-character' or\nless).\n\nIf `eval-expression-debug-on-error' is non-nil, which is the default,\nthis command arranges for all errors to enter the debugger." (interactive "P") #<bytecode 0x1000d3153>) nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

Could this be connected to https://github.com/dzop/emacs-zmq/issues/3#issuecomment-455316633? Do you have an idea on how to debug this further?

**Comment by nnicandro** [comment]
Well at least compilation works so that's good. The link in my comment is about having to also copy over the `libgcc` and `libstdc++` dll's in order for `libzmq` to work. But it looks like you can specify 
`CXXFLAGS=-static-libgcc -static-libstdc++` when compiling `libzmq` in order to work around this.

About the error: it looks like Emacs is trying to load the module file as if it were Emacs Lisp code since it is calling `eval-buffer` on the `dll`. Maybe try replacing `load-file` with `module-load` in the `zmq-load` function.

**Comment by fleimgruber** [comment]
Thanks for checking back. Where would I set `CXXFLAGS`?

Tried your suggestion for the load error, but `module-load` is not defined.
Am I missing basic module support?

**Comment by nnicandro** [comment]
If the variable `module-file-suffix` is equal to `dll` then you should have module support and modules are available in Emacs > 25. I don't know if modules are enabled by default in the Windows binaries provided by Emacs.

About `CXXFLAGS`, for right now you can set

https://github.com/dzop/emacs-zmq/blob/bc89b508ab823cc128e7a5aa3059f791edb1193f/Makefile#L95

to 

```
	./configure CXXFLAGS="-static-libgcc -static-libstdc++" --quiet --without-docs --prefix=$(ZMQ_BUILD_DIR) \
```

**Comment by fleimgruber** [comment]
The `module-file-suffix` was `nil` and I set it manually to `dll`. Will check for module support in the Windows binaries.

**Comment by nnicandro** [comment]
If it was `nil` then your Emacs wasn't built with module support.

**Comment by fleimgruber** [comment]
I compiled 26.1. just now `--with-modules` and reverted to the original `load-file` (tried `module-load` as well). Now I get:

```
Debugger entered--Lisp error: (module-open-failed "c:/Users/user/.spacemacs.d/layers/pbz/local/emacs-zmq/emacs-zmq.dll" "The specified procedure could not be found.")
  load("c:/Users/user/.spacemacs.d/layers/pbz/local/emacs-zmq/emacs-zmq.dll" nil nil t)
  load-file("c:/Users/user/.spacemacs.d/layers/pbz/local/emacs-zmq/emacs-zmq.dll")
  (progn (load-file zmq-module-file) (add-hook 'post-gc-hook (function zmq--cleanup-globrefs)))
  (if (file-exists-p zmq-module-file) (progn (load-file zmq-module-file) (add-hook 'post-gc-hook (function zmq--cleanup-globrefs))) (if (y-or-n-p "ZMQ module not found. Build it? ") (progn (let ((default-directory (file-name-directory (locate-library "zmq")))) (let (--cl-load-zmq--) (setq --cl-load-zmq-- (function (lambda (_buf status) (progn (if (string= status "finished\n") (zmq-load) (message "Something went wrong when compiling the ZMQ module!")) (remove-hook 'compilation-finish-functions --cl-load-zmq--) (exit-recursive-edit))))) (add-hook 'compilation-finish-functions --cl-load-zmq--) (compile "make") (recursive-edit))))))
  (if zmq-module-file (if (file-exists-p zmq-module-file) (progn (load-file zmq-module-file) (add-hook 'post-gc-hook (function zmq--cleanup-globrefs))) (if (y-or-n-p "ZMQ module not found. Build it? ") (progn (let ((default-directory (file-name-directory (locate-library "zmq")))) (let (--cl-load-zmq--) (setq --cl-load-zmq-- (function (lambda (_buf status) (progn (if (string= status "finished\n") (zmq-load) (message "Something went wrong when compiling the ZMQ module!")) (remove-hook 'compilation-finish-functions --cl-load-zmq--) (exit-recursive-edit))))) (add-hook 'compilation-finish-functions --cl-load-zmq--) (compile "make") (recursive-edit)))))) (user-error "Modules are not supported"))
  zmq-load()
```

**Comment by fleimgruber** [comment]
To further debug this, I installed https://github.com/lucasg/Dependencies/ and found some functions missing in the libzmq.dll

```
N/A, 24 (0x00000018), zmq_join, C:\Users\user\opt\msys64\mingw64\bin\libzmq.dll, False, None
N/A, 25 (0x00000019), zmq_leave, C:\Users\user\opt\msys64\mingw64\bin\libzmq.dll, False, None
N/A, 31 (0x0000001f), zmq_msg_group, C:\Users\user\opt\msys64\mingw64\bin\libzmq.dll, False, None
N/A, 38 (0x00000026), zmq_msg_routing_id, C:\Users\user\opt\msys64\mingw64\bin\libzmq.dll, False, None
N/A, 41 (0x00000029), zmq_msg_set_group, C:\Users\user\opt\msys64\mingw64\bin\libzmq.dll, False, None
N/A, 42 (0x0000002a), zmq_msg_set_routing_id, C:\Users\user\opt\msys64\mingw64\bin\libzmq.dll, False, None
N/A, 45 (0x0000002d), zmq_poller_add, C:\Users\user\opt\msys64\mingw64\bin\libzmq.dll, False, None
```

I do not see the pattern here, but some functions _are_ found so the MinGW build is borked it seems.

**Comment by nnicandro** [comment]
Those are all functions in the `DRAFT` API of `libzmq` which is currently required by `emacs-zmq`. But those functions should be available since `--enable-drafts=yes` is passed as a configure option when building `libzmq` in the Makefile.

**Comment by fleimgruber** [comment]
Well... I think we are getting somewhere since the libzmq.dll that is referenced is the one from MSYS2 MinGW64 install - not the built one. Where is the libzmq.dll supposed to end up?

**Comment by nnicandro** [comment]
I really have no idea on how searching for libraries works on Windows using MinGW, but it seems like when loading `emacs-zmq.dll` it is searching for the `libzmq.dll` to load instead of loading the `libzmq.dll` at the path specified with the `-L` option when compiling `emacs-zmq.dll`. Maybe you can do the equivalent of `export LD_LIBRARY_PATH=<path to libzmq.dll>` before running Emacs so that it finds the right libzmq.  Or possibly copy the `libzmq.dll` to the same directory as `emacs-zmq.dll`. The `libzmq.dll` should be in `libzmq/build/v4.3.1/bin`.

If that doesn't work, can you show the commands that you used to compile `emacs-zmq`. If you ran

```
make libzmq
make src/Makefile
make -C src install
```

it should link the right libzmq even on Windows.

Could you also show the value of the commands that are actually run when calling `make src/Makefile` (the first three lines of output) and the value of the two lines after the `configure: Verifying libzmq` line in the configure output of `make src/Makefile`.

Also useful would be the `Output variables` section of the `src/config.log` file.

**Comment by fleimgruber** [comment]
I tried putting the `libzmq.dll` next to `emacs-zmq.dll` and it seems to work now, i.e. `(require 'zmq)` evals to `zmq` without error - thanks for the support! I will now try to install `emacs-jupyter`.

**Comment by nnicandro** [comment]
You can run the tests by calling `make test`.

Also could you possibly make a pull request or describe the full steps you took for a successful build. Was there anything else that you did other than what has been discussed?

It would also be useful to have a recipe in the README for Windows users to build and install an Emacs with module support.

**Comment by fleimgruber** [comment]
`make test` looks good.

```
emacs -nw -Q -batch -L . -l ert -l zmq-tests.el \
--eval "(ert-run-tests-batch-and-exit)"
Running 11 tests (2019-02-08 22:21:15+0100)
   passed   1/11  zmq-close-socket-once
   passed   2/11  zmq-contexts
   passed   3/11  zmq-encryption
   passed   4/11  zmq-globrefs
   passed   5/11  zmq-messages
   passed   6/11  zmq-polling
   passed   7/11  zmq-send-unicode
   passed   8/11  zmq-sockets
   passed   9/11  zmq-subprocess
   passed  10/11  zmq-utility
   passed  11/11  zmq-wrong-object-type

Ran 11 tests, 11 results as expected (2019-02-08 22:21:18+0100)
```

**Comment by fleimgruber** [comment]
I will work out a PR for the changes and a section in the README with instructions.

**Comment by fleimgruber** [comment]
I think you need to make a decision on how you want to support Windows. Right now I see three options:

1. Make the build scripts aware of MinGW tools so users do not have to fiddle with them (but still need to build themselves).
2. Just add a section in the README on how to adapt the build scripts and build manually.
3. Provide the binaries as you suggested in the OP.

The section in the README should be added regardless of the chosen option IMHO. For option 3 I can provide the binaries if you lack access to a Windows box. Better yet, we could teach Travis how to build them. Depending on your decision I would work out a PR.

**Comment by nnicandro** [comment]
My intentions are to teach Travis how to build the binaries and upload them using the [release uploading](https://docs.travis-ci.com/user/deployment/releases) feature of Travis.

So I think (1) is the way to go since if a user on Windows wanted to build it themselves, they could. And this would be the easiest way to work towards Travis to build the binaries as well.

One way to do it would be to add a new shell variable `ZMQ_COMPILE_HOST` which can be used to determine if we are cross compiling in the top level Makefile. So something like

```
ifeq ($(OS),WINNT)
ZMQ_COMPILE_HOST ?= i686-w64-mingw32
else
ZMQ_COMPILE_HOST ?=
endif
```

and then use the variable when calling `configure`. This way in Travis we can just do something like

```
export ZMQ_COMPILE_HOST = ...
make
...
```

to build the binaries. I don't know if the `$(OS)` check will actually work on MinGW. You may need something like `uname`. You can then use the variable to change the Makefile targets accordingly, for example changing the `emacs-zmq.so` target to `emacs-zmq.dll`.

Also for checking the host OS in configure, see https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Canonicalizing.html

About the README, I agree that a section should be added regardless.

**Comment by fleimgruber** [comment]
See https://github.com/dzop/emacs-zmq/pull/7 for a first shot at this.

**Comment by nnicandro** [comment]
Could you download the following tarball

https://github.com/dzop/emacs-zmq/releases/download/v0.9.1/emacs-zmq-x86_64-w64-mingw32.tar.gz

and run `make test` using the dll's it contains and let me know if everything works as expected.

**Comment by fleimgruber** [comment]
I copied the Makefile, zmq.el and zmq-tests.el from the repo to a fresh directory, put in the libzmq.dll and the emacs-zmq.dll from the provided tarball and can confirm that `make test` worked as in https://github.com/dzop/emacs-zmq/issues/3#issuecomment-461951126.

**Comment by nnicandro** [comment]
Great!

**Comment by llcc** [comment]
Hi, sorry to reply here. I tested emacs-zmp on my windows by downloading the pre-compiled
dll files. zmp-subprocess failed the test.

```
emacs -nw -Q -batch -L . -l ert -l zmq-tests.el --eval "(ert-run-tests-batch-and-exit)"
Running 11 tests (2019-03-30 21:55:40+0900)
   passed   1/11  zmq-close-socket-once
   passed   2/11  zmq-contexts
   passed   3/11  zmq-encryption
   passed   4/11  zmq-globrefs
   passed   5/11  zmq-messages
   passed   6/11  zmq-polling
   passed   7/11  zmq-send-unicode
   passed   8/11  zmq-sockets
Test zmq-subprocess backtrace:
  signal(ert-test-failed (((should filter-called) :form filter-called
  ert-fail(((should filter-called) :form filter-called :value nil))
  (if (unwind-protect (setq value-408 filter-called) (setq form-descri
  (let (form-description-409) (if (unwind-protect (setq value-408 filt
  (let ((value-408 (gensym "ert-form-evaluation-aborted-"))) (let (for
  (let* ((body '((if zmq-current-context (prin1 (cons 'test-result "co
  (let ((ert--infos (cons (cons "Info: " "Subprocess wraps function wi
  (closure (t) nil (let ((ert--infos (cons (cons "Info: " "Validating
  ert--run-test-internal(#s(ert--test-execution-info :test #s(ert-test
  ert-run-test(#s(ert-test :name zmq-subprocess :documentation nil :bo
  ert-run-or-rerun-test(#s(ert--stats :selector t :tests [#s(ert-test
  ert-run-tests(t #f(compiled-function (event-type &rest event-args) #
  ert-run-tests-batch(nil)
  ert-run-tests-batch-and-exit()
  eval((ert-run-tests-batch-and-exit))
  command-line-1(("-L" "." "-l" "ert" "-l" "zmq-tests.el" "--eval" "(e
  command-line()
  normal-top-level()
Test zmq-subprocess condition:
    Info: Subprocess wraps function with context
    (ert-test-failed
     ((should filter-called)
      :form filter-called :value nil))
   FAILED   9/11  zmq-subprocess
   passed  10/11  zmq-utility
   passed  11/11  zmq-wrong-object-type

Ran 11 tests, 10 results as expected, 1 unexpected (2019-03-30 21:55:44+0900)

1 unexpected results:
   FAILED  zmq-subprocess
```

**Comment by nnicandro** [comment]
@llcc This is most likely an issues with Emacs's support for Window's subprocesses. In that test, we start a subprocess and have it send a message back to the parent Emacs process. The failure of the test means that the parent Emacs process did not receive the message within the timeout period (0.4 seconds). What is `M-x emacs-version` and your version of Windows?

Also, is this an intermittent failure? Can you run the tests a few times to see if you consistently get this error.

Finally, do other programs that use subprocesses work? For example, can you start a Python process using `M-x run-python` and interact with it normally.

**Comment by llcc** [comment]
Hi @dzop. I am on the latest `GNU Emacs 26.1 (build 1, x86_64-w64-mingw32) of 2018-06-19`.

I tested for several times, none of them worked.

A python buffer got opened by `M-x run-python`, but I cannot input anything. It says 
```
Shell native completion is disabled, using fallback
funcall-interactively: Text is read-only [14 times]
```

**Comment by nnicandro** [comment]
`M-x run-python` was just an example of a command that uses a subprocess. The command doesn't matter. What we want to figure out is if your Emacs can talk to subprocesses.

So did running `M-x run-python` actually start a subprocess and show that it was working properly? It could be broken on your system, but did it look like it was talking to a subprocess, e.g. did the buffer show the banner that is typically shown when you open a python REPL?

What about `M-x shell`? Can you run `M-x shell` and type `ls` or `dir` to see if you get proper output.

Another way to confirm that subprocesses are working is if you use `flyspell` since that also communicates with a subprocess. Do you use `flyspell`?

**Comment by llcc** [comment]
Hi, sorry to reply late.

I uploaded the screenshot, i do believe it's talking to the subprocess.
![image](https://user-images.githubusercontent.com/3996879/55554768-8e53c200-571e-11e9-9a70-dee4b81a5464.png)

And, this is the result of `list-process`:
![image](https://user-images.githubusercontent.com/3996879/55554803-a4618280-571e-11e9-9f5b-139bffdb7c29.png)

I do can use `M-x shell` and `flyspell`, they both work well.

**Comment by nnicandro** [comment]
@llcc OK it looks like more investigation is needed. Can you open up a new issue on this so that I don't forget and so that other Windows users can provide some input. In the new issue can you show the backtrace of the test results and also that your Emacs can indeed talk to other subprocesses.

I don't have a Windows machine so maybe @fleimgruber has some ideas about what could be going on.

**Comment by fleimgruber** [comment]
I have no idea off the top of my head. I would be happy to assist in debugging given a new issue containing reproducible steps or additional investigation actions.

**Comment by fleimgruber** [comment]
To get an idea about the subprocess handling, I had a look into the test "Subprocess wraps function with context" and the `zmq-start-process` function in there. I assume there might be something wrong in the `make-process` part where a `:command` such as

```
c:/Users/user/opt/emacs-26/bin/emacs -Q -batch -L c:/Users/user/.spacemacs.d/layers/user/local/emacs-zmq/ -l c:/Users/user/.spacemacs.d/layers/user/local/emacs-zmq/zmq.el --eval "(zmq--init-subprocess nil)"
```

is constructed. Could we get more debug information by setting `(setq zmq--subprocess-debug t)` or can I directly debug `zmq-start-process` from a running emacs? I tried but all the checks for non-interactivity in there lead to the error "Not a subprocess".

**Comment by nnicandro** [comment]
It doesn't look like `zmq--subprocess-debug` will give any useful information in this case since, by default, when an error happens in the subprocess an error is raised in the parent Emacs process. Setting `zmq--subprocess-debug` to `t` just causes the subprocess to also include a backtrace along with the error and to print out the `stderr` of the subprocess to the `*Message*` buffer of the parent Emacs process.

The "Not a subprocess" errors happen in `zmq--init-subprocess` and `zmq-subprocess-read`. Really it should only be called in `zmq-subprocess-read` since that calls `read-minibuffer` and it expects what it reads to be in the format that `zmq-subprocess-send` uses.

I don't think there would be any issues in `zmq--init-subprocess` since all it does is call the function `zmq-start-process` is given.
 
So maybe the issue is the encoding/decoding that is happening in `zmq-subprocess-read` and `zmq-subprocess-send`. 

[1] is a stripped down version of `zmq-start-process` that does not go through `zmq-subprocess-read` or `zmq-subprocess-send`. If @llcc can run the below example, then we know that the issue is probably in the encoding/decoding of the function sent to the subprocess.

```emacs-lisp
(let ((proc
       (nn/test-process
        (lambda (event)
          (message "%s" event))
        "(prin1 '(event 1 2 3))")))
  (sleep-for 0.5))
```

The function passed to `nn/test-process` is just the filter function that will be run in the current Emacs process, the string is the command to evaluate in the subprocess. So the `prin1` call will happen in the subprocess and it will print out the list `'(event 1 2 3)` to its stdout which is then read by the parent Emacs process and eventually passed to the filter function.

[1]
```emacs-lisp
(defun nn/test-process (filter cmd)
  (let* ((zmq-path (locate-library "zmq"))
         ;; stderr is split from stdout since the former is used by
         ;; Emacs to print messages that we don't want intermixed
         ;; with what the subprocess returns.
         (stderr (make-pipe-process
                  :name "zmq stderr"
                  :buffer (generate-new-buffer " *zmq*")
                  :noquery t
                  :stop t))
         (process (make-process
                   :name "zmq"
                   :buffer (generate-new-buffer " *zmq*")
                   :noquery t
                   :connection-type 'pipe
                   :coding-system 'no-conversion
                   :filter #'zmq--subprocess-filter
                   :sentinel #'zmq--subprocess-sentinel
                   :stderr stderr
                   :command (list
                             (file-truename
                              (expand-file-name invocation-name
                                                invocation-directory))
                             "-Q" "-batch"
                             "-L" (file-name-directory zmq-path)
                             "-l" zmq-path "--eval" cmd))))
    (process-put process :stderr stderr)
    (process-put process :filter filter)
    (with-current-buffer (process-buffer process)
      (let ((inhibit-read-only t))
        (erase-buffer))
      (special-mode))
    ;; (zmq-subprocess-send process (macroexpand-all sexp))
    process))
```
