### ISSUE TITLE
include a `.dylib`-extensioned copy of the `.so` file for the macOS releases

### ISSUE THREAD

**Issue by NightMachinery** [dzop/emacs-zmq#35]
Some package in my emacs (I did not trace which it was, probably emacs-jupyter) expects the dynamic module downloaded to have a `.dylib` extension on emacs. When I build it from source, it automatically does this:
```
...
mkdir -p /Users/evar/.emacs.d.doom/.local/straight/build-28.0.60/zmq/
cp src/.libs/emacs-zmq.so /Users/evar/.emacs.d.doom/.local/straight/build-28.0.60/zmq//emacs-zmq.dylib

Compilation finished at Wed Oct 13 17:56:38
```

**Comment by nnicandro** [comment]
This should be fixed by f3213ce9d0c1aa6002efe4b7da040c425055a7e8.  `.dylib` will be the default on macosx on the next release.
