### ISSUE TITLE
failed to build emacs-zmq module on an apple silicon Mac 

### ISSUE THREAD

**Issue by ltmsyvag** [dzop/emacs-zmq#44]
update:

I was later able to build the `emacs-zmq.so` file after simply deleting and reinstalling the emacs-zmq package. I assume my previous attempt to build the the file left some traces in the package directory that prevented a successful building. 

-------------

I use emacs-jupyter, which depends on emacs-zmq, in addition I use a m2 MacBook. I was able to build the `emacs-zmq.so` module on my old intel MacBook, but somehow I failed to build it on my m2 MacBook. If I run `make` in the emacs-zmq directory, I get the following messages:

```
make EMACS=/Applications/Emacs.app/Contents/MacOS/Emacs
/Library/Developer/CommandLineTools/usr/bin/make configure
cd src && ./configure CPPFLAGS="" \
        --prefix=/Users/xxxxxxx/.emacs.d/elpa/zmq-20230214.36 \
		--enable-shared=emacs-zmq --enable-static=zeromq \
		--without-docs --enable-drafts=yes --enable-libunwind=no \
		--disable-curve-keygen --disable-perf --disable-eventfd
checking for a BSD-compatible install... /opt/homebrew/bin/ginstall -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /opt/homebrew/bin/gmkdir -p
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... none
checking for ar... ar
checking the archiver (ar) interface... ar
checking build system type... aarch64-apple-darwin22.4.0
checking host system type... aarch64-apple-darwin22.4.0
./configure: line 4403: syntax error near unexpected token `ZMQ,'
./configure: line 4403: `PKG_CHECK_MODULES(ZMQ, libzmq,'
make[1]: *** [configure] Error 2
make: *** [src/Makefile] Error 2
```

I would appreciate any interpretation about what could be wrong. For more information, before the building, I installed via homebrew `automake`, `autoconf`, `libtool`, and `pkg-config`.

**Comment by chookity-pokk** [comment]
Sorry to reopen this but I am having the same error. I have installed the same packages via homebrew and when trying to install this package it always fails to install. I've tried deleting the package, restarting emacs and installing again. Which didn't work so I looked for any leftovers from the initial install and couldn't find any. I tried after restarting the laptop and it still hasn't worked. 

Though my error message seems to be a bit different,

```
-*- mode: compilation; default-directory: "~/.emacs.d/elpa/zmq-20230608.1856/" -*-
Compilation started at Tue Aug 29 07:27:13

make EMACS=/Applications/Emacs.app/Contents/MacOS/Emacs-arm64-11
cd src && autoreconf -i
bash: autoreconf: command not found
make: *** [src/configure] Error 127

Compilation exited abnormally with code 2 at Tue Aug 29 07:27:14
```

**Comment by chookity-pokk** [comment]
Well shoot, I spoke too soon. Honestly I should open issues more often because I swear right after doing so I always solve my problem. The solution for me was to install `zmq` with `homebrew install zmq` and then install `jupyter` via emacs. After that everything built just fine and I was able to run jupyter blocks in org mode.

**Comment by danking** [comment]
FWIW, for future folks, I ran the following (though I don't think zeromq was necessary):
```
brew install pkg-config zeromq autoconf automake libtool
```

I then had to manually go to the zmq emacs package src directory (the version will likely be different for you):
```
cd ~/.emacs.d/elpa/zmq-20241006.1857/src
```
And within there I had to run `autoreconf -i`. I am not sure why `(zmq-load)` skips the autoreconf command after running it just once, even if it fails.

**Comment by marioaquino** [comment]
^^ This helped me! 🙏🏼
