### ISSUE TITLE
Need to run `./configure` manually in `~/.emacs.d/elpa/zmq-20230608.1856/src/libzmq`, problems with libstdc++

### ISSUE THREAD

**Issue by alexpdp7** [dzop/emacs-zmq#49]
Compiling the zmq module failed like:

```
$ make all
Making all in libzmq
make[1]: Entering directory '/home/alex/.emacs.d/elpa/zmq-20230608.1856/src/libzmq'
make[1]: *** No rule to make target 'all'.  Stop.
make[1]: Leaving directory '/home/alex/.emacs.d/elpa/zmq-20230608.1856/src/libzmq'
make: *** [Makefile:608: all-recursive] Error 1
$ make
Making all in libzmq
make[1]: Entering directory '/home/alex/.emacs.d/elpa/zmq-20230608.1856/src/libzmq'
make[1]: *** No rule to make target 'all'.  Stop.
make[1]: Leaving directory '/home/alex/.emacs.d/elpa/zmq-20230608.1856/src/libzmq'
make: *** [Makefile:608: all-recursive] Error 1
```

, until I went into `src/libzmq` and ran `./configure` myself.

After that, compilation fails with:

```
/usr/bin/ld: cannot find -l:libstdc++.a
```

I'm in CentOS 9 Stream and `libstdc++-devel` and `gcc-c++` is installed, though.

**Comment by samJcrawford** [comment]
Spent a while bashing my head at this, eventually stumbled across a [related issue](https://github.com/rordenlab/dcm2niix/issues/137) in a separate project.

On fedora, (in a distrobox) I solved this with `sudo dnf install libstdc++-static`.

**Comment by nnicandro** [comment]
Closing as issue seems to be resolved.
